// Liquid Glass styles for react-select — Glass Level 3 dropdowns

const C = {
  blue: '#3b82f6',
  blueH: '#2563eb',
  text1: '#0f172a',
  text2: '#475569',
  text3: '#64748b',
  text4: '#94a3b8',
  surface: '#ffffff',
  surfaceR: '#f8fafc',
  // Navy-tinted borders & shadows (Liquid Glass system)
  border: 'rgba(30,58,95,0.1)',
  borderFocus: 'rgba(59,130,246,0.4)',
  shadow: '0 1px 2px rgba(30,58,95,0.03)',
  shadowFocus: '0 0 0 3px rgba(59,130,246,0.15)',
  // Glass Level 3 tokens
  glass3: 'rgba(255,255,255,0.65)',
  glass3Border: 'rgba(255,255,255,0.35)',
  glass3Shadow: '0 2px 16px rgba(30,58,95,0.08), inset 0 1px 0 rgba(255,255,255,0.6)',
}

export const glassStyles = {
  control: (base, state) => ({
    ...base,
    minHeight: 36,
    fontSize: 13,
    fontFamily: 'inherit',
    fontWeight: 450,
    letterSpacing: '-0.01em',
    background: C.surface,
    border: `1.5px solid ${state.isFocused ? C.borderFocus : state.hasValue ? 'rgba(59,130,246,0.3)' : C.border}`,
    borderRadius: 8,
    boxShadow: state.isFocused ? C.shadowFocus : C.shadow,
    cursor: 'pointer',
    transition: 'all 0.2s cubic-bezier(0.4,0,0.2,1)',
    '&:hover': {
      borderColor: C.blue,
      boxShadow: '0 1px 4px rgba(30,58,95,0.04), 0 1px 2px rgba(30,58,95,0.02)',
    },
  }),
  valueContainer: (base) => ({
    ...base,
    padding: '0 14px',
    gap: 4,
  }),
  input: (base) => ({
    ...base,
    margin: 0,
    padding: 0,
    fontSize: 13,
    color: C.text1,
    fontWeight: 450,
  }),
  placeholder: (base) => ({
    ...base,
    fontSize: 13,
    color: C.text4,
    fontWeight: 400,
  }),
  singleValue: (base) => ({
    ...base,
    fontSize: 13,
    color: C.text1,
    fontWeight: 500,
  }),
  dropdownIndicator: (base, state) => ({
    ...base,
    padding: '0 6px',
    color: state.isFocused ? C.blue : C.text4,
    transition: 'color 0.15s, transform 0.2s',
    transform: state.selectProps.menuIsOpen ? 'rotate(180deg)' : 'rotate(0)',
    '&:hover': { color: C.blue },
    svg: { width: 15, height: 15 },
  }),
  indicatorSeparator: () => ({ display: 'none' }),
  clearIndicator: (base) => ({
    ...base,
    padding: '0 4px',
    color: C.text4,
    borderRadius: 4,
    transition: 'all 0.15s',
    '&:hover': { color: '#ef4444', background: 'rgba(239,68,68,0.08)' },
    svg: { width: 14, height: 14 },
  }),
  menu: (base) => ({
    ...base,
    marginTop: 4,
    borderRadius: 16,
    // Liquid Glass Level 3
    background: C.glass3,
    backdropFilter: 'blur(16px) saturate(160%)',
    WebkitBackdropFilter: 'blur(16px) saturate(160%)',
    border: `1px solid ${C.glass3Border}`,
    boxShadow: C.glass3Shadow,
    zIndex: 50,
    overflow: 'hidden',
    animation: 'menuSlideIn 0.15s ease-out',
  }),
  menuList: (base) => ({
    ...base,
    maxHeight: 240,
    padding: 4,
    '::-webkit-scrollbar': { width: 6 },
    '::-webkit-scrollbar-track': { background: 'transparent' },
    '::-webkit-scrollbar-thumb': { background: 'rgba(148,163,184,0.3)', borderRadius: 3 },
  }),
  option: (base, state) => ({
    ...base,
    fontSize: 12,
    padding: '8px 12px',
    borderRadius: 6,
    margin: '1px 0',
    color: state.isSelected ? C.blue : state.isFocused ? C.text1 : C.text2,
    fontWeight: state.isSelected ? 600 : state.isFocused ? 500 : 400,
    background: state.isSelected
      ? 'rgba(59,130,246,0.1)'
      : state.isFocused
        ? 'rgba(59,130,246,0.05)'
        : 'transparent',
    cursor: 'pointer',
    transition: 'all 0.1s',
    '&:active': { background: 'rgba(59,130,246,0.15)', transform: 'scale(0.99)' },
  }),
  multiValue: (base) => ({
    ...base,
    background: '#f0f5ff',
    border: '1px solid rgba(59,130,246,0.15)',
    borderRadius: 6,
    maxWidth: 120,
  }),
  multiValueLabel: (base) => ({
    ...base,
    fontSize: 10.5,
    fontWeight: 600,
    color: C.blue,
    padding: '2px 4px 2px 6px',
  }),
  multiValueRemove: (base) => ({
    ...base,
    color: 'rgba(59,130,246,0.5)',
    paddingLeft: 2,
    paddingRight: 4,
    borderRadius: '0 6px 6px 0',
    transition: 'all 0.15s',
    '&:hover': { background: 'rgba(239,68,68,0.12)', color: '#ef4444' },
  }),
  noOptionsMessage: (base) => ({
    ...base,
    fontSize: 12,
    color: C.text4,
    padding: '12px 16px',
    fontStyle: 'italic',
  }),
  loadingMessage: (base) => ({
    ...base,
    fontSize: 12,
    color: C.text3,
    padding: '12px 16px',
  }),
  menuPortal: (base) => ({ ...base, zIndex: 9999 }),
}

export const glassTheme = (theme) => ({
  ...theme,
  borderRadius: 8,
  spacing: { ...theme.spacing, controlHeight: 36, menuGutter: 4 },
  colors: {
    ...theme.colors,
    primary: C.blue,
    primary75: 'rgba(59,130,246,0.18)',
    primary50: 'rgba(59,130,246,0.12)',
    primary25: 'rgba(59,130,246,0.06)',
    neutral20: C.border,
    neutral30: C.borderFocus,
    neutral50: C.text4,
    neutral80: C.text1,
  },
})
